name: Semgrep-SAST-Ahmed-Perfect

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  semgrep_scan:
    name: "Scan Complet - Ahmed"
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      security-events: write # Obligatoire pour l'onglet Security

    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execution de Semgrep
        # On force le scan sur les dossiers spécifiques pour ne rien rater
        # On utilise 'p/security-audit' pour détecter ton eval() et ton innerHTML
        run: |
          semgrep scan \
            --sarif \
            --config="p/default" \
            --config="p/security-audit" \
            --config="p/javascript" \
            --config="p/xss" \
            --config="p/dockerfile" \
            --config="p/nginx" \
            --output=semgrep_results.sarif \
            src/ Dockerfile nginx/

      - name: Upload vers GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep_results.sarif
        if: always()